### ISSUE TITLE
RAM usage

### ISSUE THREAD

**Issue by ravelab** [arduino-libraries/ArduinoBearSSL#11]
Thank you for this great library. It works great but is using more than 60% of my available RAM. Is there any way to reduce the BearSSL memory usage (with compilation or linking options, removing some BearSSL source code ...etc)?

**Comment by ravelab** [comment]
it looks like I can change BearSSLClient _iobuf[8192 + 85 + 325] to _iobuf[1024 + 85 + 325] to save 7K RAM usage.

**Comment by TinkTechPH** [comment]
Is this the minimum applicable size for the buffer?
