### ISSUE TITLE
  sslClient.setInsecure(BearSSLClient::SNI::Insecure);

### ISSUE THREAD

**Issue by TheEngineer2020** [arduino-libraries/ArduinoBearSSL#30]
Good day,

We are developing an Arduino based device that sends an https post to a server. We use the Arduino MKR Zero and an ethernet shield. When we use this function:

  sslClient.setInsecure(BearSSLClient::SNI::Insecure);

We get this error when the compilation is done:

'class BearSSLClient' has no member named 'setInsecure'

Do you know what could be the origin of this error?

**Comment by manchoz** [comment]
@TheEngineer2020 `setInsecure` is a brand new method and it is not yet included in the version of the library available on the Library Manager in the IDE or the CLI.

You need to install the repo version of the GitHub library.

PLEASE, be VERY careful when enabling this feature and don't forget to remove it while in production.

**Comment by aentinger** [comment]
@TheEngineer2020 A new version of `ArduinoBearSSL` ([v1.5.0](https://github.com/arduino-libraries/ArduinoBearSSL/releases/tag/1.5.0)) has been release which contains this method. Other than that I can only echo @manchoz words ...
> PLEASE, be VERY careful when enabling this feature and don't forget to remove it while in production.

**Comment by TheEngineer2020** [comment]
Thank you very much, you are awesome.
