### ISSUE TITLE
Handshake SSL certificate

### ISSUE THREAD

**Issue by elexal** [arduino-libraries/ArduinoBearSSL#52]
hello friend
how can I use this function so that it recevies Auto handshake without certificate???
exp : when using class esp8266secure can get data handshake & its dosent need cert.h class or function & gets the certificate automaticaly the same as chrome browser when searching the web site
thx

**Comment by per1234** [comment]
Hi @elexal. Thanks for your interest in this open source project.
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your question over there:

https://forum.arduino.cc/c/using-arduino/networking-protocols-and-devices/27
