### ISSUE TITLE
undefined reference to `_gettimeofday' when compiling on a Teensy4.0

### ISSUE THREAD

**Issue by gannaramu** [arduino-libraries/ArduinoBearSSL#54]
I keep getting ``` undefined reference to `_gettimeofday``` issue when importing the ArduinoBearSSL library.

undefined reference to `_gettimeofday'

```
Linking .pio\build\teensy40\firmware.elf
c:/users/ganna/.platformio/packages/toolchain-gccarmnoneeabi/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/lib/armv7e-m/fpu/fpv5-d16\libc.a(lib_a-gettimeofdayr.o): In function `_gettimeofday_r':
gettimeofdayr.c:(.text._gettimeofday_r+0x10): undefined reference to `_gettimeofday'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\teensy40\firmware.elf] Error 1
```

the fix mentioned https://github.com/arduino/Arduino/issues/9413 seems to solve it.  

But wanted to understand the reason for this issue? any help is appreciated.

Thanks

**Comment by Jeroen88** [comment]
Maybe it has something to do with [this](https://github.com/arduino-libraries/ArduinoBearSSL/blob/ff4b17d80c278012f13242f553837a25b17c015e/src/bearssl/inner.h#L416) line?

**Comment by aentinger** [comment]
It might be the case. Possible Teensy's platform defines cause `BR_USE_UNIX_TIME` to be set to `1` consequently requiring linking to `_gettimeofday`. In this case it would be as simple as adding a statement preventing this. @PaulStoffregen what would be a suitable define set in all Teensy platforms?

**Comment by Jeroen88** [comment]
I do not know what compiler tag TEENSY defines, but in my port to the ESP32 I added

`#if defined __unix__ || defined __linux__ || defined ESP32`

and now it works like a charm.

My port to the ESP32 is [here](https://github.com/Jeroen88/ESP32BearSSL)

**Comment by gannaramu** [comment]
I guess the teensy 4.x have the defines as:
```
#if defined(__IMXRT1052__) || defined(__IMXRT1062__)

```

**Comment by PaulStoffregen** [comment]
Added _gettimeofday to Teensy 4.x core library.
https://github.com/PaulStoffregen/cores/commit/50342d77de1b495ee359e78c12153bb6532a5727

**Comment by aentinger** [comment]
> Added _gettimeofday to Teensy 4.x core library. [PaulStoffregen/cores@50342d7](https://github.com/PaulStoffregen/cores/commit/50342d77de1b495ee359e78c12153bb6532a5727)

Thank you :bow:
