### ISSUE TITLE
ArduinoBearSsl without eec

### ISSUE THREAD

**Issue by bvernham** [arduino-libraries/ArduinoBearSSL#59]
How do you use Bearssl without using a crypto chip.  How do you atrach the private, public, and certificate?

Thanks

**Comment by aentinger** [comment]
I suggest reading the [BearSSL](https://bearssl.org/) documentation and/or poll the forum. A github issue is the wrong medium for support questions.

**Comment by bvernham** [comment]
Well the problem is the example connecting to aws does not work or as the comments read works hit or miss and seem to be something to do with how bearssl accepts certificates.There does not seem to be a whole lot of support for this issue.  This is why i bouggt the board but can't even get a canned example to.work.On Jan 12, 2022 12:16 AM, Alexander Entinger ***@***.***> wrote:
I suggest reading the BearSSL documentation and/or poll the forum. A github issue is the wrong medium for support questions.

—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
You are receiving this because you authored the thread.Message ID: ***@***.***>


____________________________________________________________Top News - Sponsored By Newser3-Time Olympian Deon Lendore Dies in Car AccidentNorth Korea Launches 2nd Hypersonic Missile in a WeekLawmaker's Tweet About Wife Shoveling Snow Goes Viral
